# Config file for automatic testing at travis-ci.org

language: python
sudo: false
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
matrix:
  allow_failures:
    - env: TOXENV=py33
    - env: TOXENV=py34

install:
  - travis_retry pip install tox

script:
  - tox
