# Prefer docker containers
sudo: required

language: python

python:
  - "2.7"

cache: pip

matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27
  - python: "3.4"
    env: TOXENV=py34
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.6"
    env: TOXENV=py36
  - python: "3.7"
    dist: xenial
    env: TOXENV=py37
  - python: "2.7"
    env: TOXENV=py27-flake8
  - python: "3.7"
    dist: xenial
    env: TOXENV=py37-flake8
  - python: "pypy"
    env: TOXENV=pypy

  fast_finish: true

install:
  - travis_retry pip install --upgrade pip setuptools tox ppu

script:
  - tox

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: phd
  password:
    secure: QxKzdSfC8GaU77gb5hjAy4e2s28tWL467wJDluO5JttbAAT2vMsK88MWWZjm0gWcyY9giWCLMbIj735MTmfKzuDXvphDD+9qOBbonMszBP4uDEMcKKNALUoxBDNDksgb0d6qPclH/3u2BnIRhqxfUudYpmp4+kwX3tSziakQJCfwCT92bXEm3ET+nNBhHQNfthfhnb0voHtPwY6gjoz68WTLKfbh9uNZ8MiM90GA5b6z/JVLyOTm8LoEV4oMdefZy78A3qgwyUfXsmO/d+j18C2QSrMQfXgx7kpnRE0D2uQ26SnYRB/SFVXHmHklTTa7BIxYNhRsbOeoxbcRpNSHYIhMKunQinptwMjlLicVfjqUXfG9cg8vuTVQif0SdJu9DRtYb1Yca98xiznr9wN5u9ZuG4twuOcfuZTUKzCmEe2fHQtIB4SeazwRzVAL0UQ7aOI/ZqQdJIH3Ih4bqtcBivXS8j47AKIa/m0lArKh/kuZkiOd4IGVRFLCyRzh+t6TDzcWO7ly7/zjvaYAip2xJY/eTWV0bg8Vq6eWCY8otj32EkJ5X7xktc5dRwNQv/hfK88anEnpFdkQpaRWjMmX/3TK8DLOlnMEf5NIZfytostZkSPhpaPgYMb2HNFWKUyOpRLIMOQPyADFZJkTULq3K1D548W+4QFhljO9cwVTfsQ=
  distributions: sdist bdist_wheel
  on:
    tags: true
  skip_existing: true

before_cache:
  - remove-old-files.py -o 180 ~/.cache/pip
