# Install and test Cheetah on windows
# Heavily inspired by Oliver Grisel's appveyor-demo (https://github.com/ogrisel/python-appveyor-demo)
version: '{branch}-{build}'

# Only test maint, master and pull requests; skip tags.
# Other branches can allow themselves.
branches:
  only:
    - maint
    - master
    - next
skip_branch_with_pr: false
skip_tags: false

cache:
  - '%LOCALAPPDATA%\pip\Cache'
    # Cache chocolatey-installed packages (PyPy)
  - C:\ProgramData\chocolatey\bin -> appveyor.yml, devscripts\CI\appveyor_install_pypy.cmd
  - C:\ProgramData\chocolatey\lib -> appveyor.yml, devscripts\CI\appveyor_install_pypy.cmd

# Match travis
clone_depth: 50

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C devscripts\\CI\\run_with_env.cmd"

  matrix:
    - TOXENV: "py27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python27"
    - TOXENV: "py27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python27-x64"
    - TOXENV: "py34"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python34"
    - TOXENV: "py34"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python34-x64"
    - TOXENV: "py35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python35"
    - TOXENV: "py35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python35-x64"
    - TOXENV: "py36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python36"
    - TOXENV: "py36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python36-x64"
    - TOXENV: "py37"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python37"
    - TOXENV: "py37"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python37-x64"
    - TOXENV: "pypy"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\tools\\pypy\\pypy"

install:
  # Ensure we use the right python version
  - "SET PATH=%PYTHON_HOME%;%PYTHON_HOME%\\Scripts;%PATH%"
  - "SET TOXPYTHON=%PYTHON_HOME%\\python.exe"
  - if "%TOXENV%" == "pypy" devscripts\\CI\\appveyor_install_pypy.cmd
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - if "%TOXENV%" == "pypy" SET TOXPYTHON=pypy.exe
  - if "%TOXENV%" == "pypy" pypy --version
  - "python -m pip install --upgrade \"pip < 19.1\" setuptools"
  - "pip install --upgrade \"tox < 3.1\" ppu"
  - "pip --version"

# No build step - _namemapper extension will be built under tox
build: false

test_script:
  - "%CMD_IN_ENV% tox"

after_test:
  # If tests are successful and we've tested a tag, create binary package
  - if "%APPVEYOR_REPO_TAG%" == "true" (
      pip install --upgrade wheel &&
      %CMD_IN_ENV% python setup.py bdist_wheel &&
      ls dist
    )
  - remove-old-files.py -o 180 %LOCALAPPDATA%\\pip\\Cache

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report
  - path: dist\*
